# -*- coding: utf-8 -*-
"""knn_44features_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbziMEgKj7kf_nQKuRASH8-lJBMSEpa-
"""

import joblib
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    roc_auc_score,
    roc_curve,
    precision_score,
    recall_score,
    f1_score,
)

# load the already-prepared 44-feature split directly from pkl
X_train, X_val, X_test, y_train, y_val, y_test = joblib.load('44features.pkl')

print('X_train shape:', X_train.shape)
print('X_val shape:  ', X_val.shape)
print('X_test shape: ', X_test.shape)
print(X_test.head())

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print(f'Train size: {len(X_train_scaled):,}')
print(f'Val size:   {len(X_val_scaled):,}')
print(f'Test size:  {len(X_test_scaled):,}')

k_range = range(1, 26)
cv_scores = []

for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train_scaled, y_train, cv=5, scoring='accuracy')
    cv_scores.append(scores.mean())
    print(f'K={k:2d}  CV Accuracy={scores.mean():.4f}')

best_k = list(k_range)[int(np.argmax(cv_scores))]
print(f'\nBest K = {best_k}  (CV accuracy = {max(cv_scores):.4f})')

knn_final = KNeighborsClassifier(n_neighbors=best_k)
knn_final.fit(X_train_scaled, y_train)

y_pred = knn_final.predict(X_test_scaled)
y_prob = knn_final.predict_proba(X_test_scaled)[:, 1]

acc = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print(f'Test Accuracy : {acc:.4f}')
print(f'ROC-AUC       : {roc_auc:.4f}')
print()
print(classification_report(y_test, y_pred, target_names=['No Default', 'Default']))

# final visualisation
fig = plt.figure(figsize=(16, 12))
fig.patch.set_facecolor('#0f1117')
gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.35)

# A. K vs CV Accuracy
ax1 = fig.add_subplot(gs[0, 0])
ax1.set_facecolor('#1a1d27')
ax1.plot(
    k_range, cv_scores,
    color='#7c6af7',
    linewidth=2.5,
    marker='o',
    markersize=5,
    markerfacecolor='white',
    markeredgecolor='#7c6af7'
)
ax1.axvline(best_k, color='#f7c948', linestyle='--', linewidth=1.8, label=f'Best K={best_k}')
ax1.set_xlabel('Number of Neighbors (K)', color='white')
ax1.set_ylabel('CV Accuracy', color='white')
ax1.set_title('K vs Cross-Validation Accuracy', color='white', fontsize=12, fontweight='bold')
ax1.tick_params(colors='white')
for spine in ax1.spines.values():
    spine.set_color('#2e3148')
ax1.legend(facecolor='#2e3148', labelcolor='white')

# B. Confusion Matrix
ax2 = fig.add_subplot(gs[0, 1])
ax2.set_facecolor('#1a1d27')
cm = confusion_matrix(y_test, y_pred)
ax2.imshow(cm, cmap='Blues')
for i in range(2):
    for j in range(2):
        ax2.text(j, i, f'{cm[i, j]:,}', ha='center', va='center', color='white', fontsize=14, fontweight='bold')
ax2.set_xticks([0, 1])
ax2.set_yticks([0, 1])
ax2.set_xticklabels(['No Default', 'Default'], color='white')
ax2.set_yticklabels(['No Default', 'Default'], color='white')
ax2.set_xlabel('Predicted', color='white')
ax2.set_ylabel('Actual', color='white')
ax2.set_title('Confusion Matrix', color='white', fontsize=12, fontweight='bold')
ax2.tick_params(colors='white')
for spine in ax2.spines.values():
    spine.set_color('#2e3148')

# C. ROC Curve
ax3 = fig.add_subplot(gs[1, 0])
ax3.set_facecolor('#1a1d27')
fpr, tpr, _ = roc_curve(y_test, y_prob)
ax3.plot(fpr, tpr, color='#7c6af7', linewidth=2.5, label=f'AUC = {roc_auc:.3f}')
ax3.plot([0, 1], [0, 1], color='#555', linestyle='--', linewidth=1.5)
ax3.set_xlabel('False Positive Rate', color='white')
ax3.set_ylabel('True Positive Rate', color='white')
ax3.set_title('ROC Curve', color='white', fontsize=12, fontweight='bold')
ax3.tick_params(colors='white')
for spine in ax3.spines.values():
    spine.set_color('#2e3148')
ax3.legend(facecolor='#2e3148', labelcolor='white')

# D. Metrics Table
ax4 = fig.add_subplot(gs[1, 1])
ax4.set_facecolor('#1a1d27')
ax4.axis('off')

metrics = {
    'Accuracy': f'{acc:.4f}',
    'ROC-AUC': f'{roc_auc:.4f}',
    'Precision (Default)': f'{precision_score(y_test, y_pred, zero_division=0):.4f}',
    'Recall (Default)': f'{recall_score(y_test, y_pred, zero_division=0):.4f}',
    'F1-Score (Default)': f'{f1_score(y_test, y_pred, zero_division=0):.4f}',
    'Best K': str(best_k),
    'Train size': f'{len(X_train_scaled):,}',
    'Val size': f'{len(X_val_scaled):,}',
    'Test size': f'{len(X_test_scaled):,}',
}

rows = [[k, v] for k, v in metrics.items()]
tbl = ax4.table(
    cellText=rows,
    colLabels=['Metric', 'Value'],
    cellLoc='center',
    loc='center',
    bbox=[0.05, 0.05, 0.9, 0.9]
)
tbl.auto_set_font_size(False)
tbl.set_fontsize(11)

for (r, c), cell in tbl.get_celld().items():
    cell.set_facecolor('#2e3148' if r == 0 else '#1a1d27')
    cell.set_text_props(color='white', fontweight='bold' if r == 0 else 'normal')
    cell.set_edgecolor('#3a3d55')

ax4.set_title('Model Summary', color='white', fontsize=12, fontweight='bold', pad=10)

fig.suptitle(
    'KNN Credit Default Classifier (44 Features from PKL)',
    color='white',
    fontsize=15,
    fontweight='bold',
    y=0.98
)

plt.savefig('knn_pkl_only_44features_results.png', dpi=150, bbox_inches='tight', facecolor='#0f1117')
plt.show()

joblib.dump(knn_final, 'knn_44features.pkl')
joblib.dump(scaler, 'knn_44features_scaler.pkl')

print('Saved:')
print('knn_44features.pkl')
print('knn_44features_scaler.pkl')